port: 5050
delay_min_ms: 1000
delay_max_ms: 1500
special_keyword_threshold: 3

stellenwerk_link: "https://www.stellenwerk.de/hamburg"
stellenwerk_pages: 6

stepstone_link: "https://www.stepstone.de/jobs/teilzeit/in-hamburg?action=facet_selected%3bdisciplines%3bIngenieurwesen&wt=80002&di=IT&di=Ingenieurwesen"
stepstone_pages: 5
keywords:
  - "Werkstudent"
  - "Studierende"
  - "Informatik"
  - "Computer"
  - "Büro"
  - "Office"
  - "Working Student"
  - "Praktikum"
  - "Praktikant"
  - "Junior"
  - "Machine Learning"
  - "Deep Learning"
  - "Computer Vision"
  - "Engineer"
  - "Entwickler"
  - "Data Engineer"
  - "Data Scientist"
  - "NLP"
  - "Python"
  - "PyTorch"
  - "TensorFlow"
  - "Scikit-learn"
  - "OpenCV"
  - "Image Segmentation"
  - "Predictive Modeling"
  - "Feature Engineering"
  - "Git"
  - "14€"
  - "15€"
  - "16€"
  - "17€"
  - "18€"
  - "19€"
  - "20€"
  - "Excel"
  - "CNN"
  - "SVM"
  - "LLM"
  - "Softwareentwickler"
  - "Software Engineer"
  - "Backend"
  - "Full Stack"
  - "C#"
  - ".NET"
  - "ASP.NET Core"
  - "Web API"
  - "SignalR"
  - "Entity Framework"
  - "React"
  - "JavaScript"
  - "Java"
  - "C++"
  - "Onion Architecture"
  - "MVC"
  - "Apache"
  - "Cordova"
  - "IoT Engineer"
  - "Embedded"
  - "Systemautomatisierung"
  - "Automation"
  - "ESP32"
  - "Arduino"
  - "MQTT"
  - "Docker"
  - "Git"
  - "CI/CD"
  - "Linux"
  - "Bash"
  - "SQL"
  - "Server"
  - "IT"
  - "IT-Support"
  - "IT-Administration"
  - "Qualitätssicherung"
  - "Testing"
  - "Machine Learning"
  - "ML"
  - "AI"
  - "KI"
  - "Python"
  - "Computer Vision"
  - "Data Engineer"
  - "Softwareentwickler"
  - "Software Engineer"
  - "Backend"
  - "Full Stack"
  - "C#"
  - ".NET"
  - "Java"
  - "C++"
  - "IoT"
  - "IT-Administration"
  - "Qualitätssicherung"
  - "Software"
  - "Backend"
  - "Developer"
  - "Praktikum"
  - "Junior"
  - "Informatik"
  - "Hilfskraft"
  - "Studentische"
  - "Embedded Systems"
  - "Hardware Engineer"
  - "Sensoren"
  - "Scientist"
  - "Research"
  - "Software"
  - "Support"
  - "Website"
  - "Wordpress"
  - "Bar"
  - "Restaurant"
negative_keywords:
  - "Senior"
  - "Lead"
  - "Manager"
  - "Expert"
  - "Principal"
  - "Head of"
  - "Leitung"
  - "MRI"
  - "Vollzeit"
  - "Full-time"
  - "C1"
  - "C2"
  - "Bauingenieur"
  - "Ingenieurbau"
  - "Verkauf"
  - "Bereichsleiter"
  - "Verkäufer"
  - "Tiefbau"
  - "SAP"
  - "Deutschkenntnisse"
  - "Bauprojekte"
  - "mehrjähriger Erfahrung"
  - "years of experience"
