port: 4567
page_size: 20
app_states:
  - "Not Applied"
  - "Applied"
  - "Rejected"
  - "Interview"
  - "Offer"

cv_types:
  - "Software"
  - "Hardware"
  - "Data"
  - "General"
delay_min_ms: 1000
delay_max_ms: 1500
special_keyword_threshold: 3

# API Keys
gemini_api_key: "YOUR_GEMINI_API_KEY_HERE"

# Evaluator Settings
evaluator_model: "gemini-2.5-flash"
evaluator_delay_s: 15
cv_paths:
  - "cvs/my_cv.pdf"
  
stellenwerk_link: "https://www.stellenwerk.de/CITY"
stellenwerk_pages: 2

stepstone_link: "https://www.stepstone.de/jobs/teilzeit/in-hamburg?xx-FILTERS-xx"
stepstone_pages: 1
keywords:
  - "Werkstudent"
  - "working student"
  - "Informatik"
negative_keywords:
  - "Senior"
  - "Lead"
  - "Manager"
  - "Expert"