port: 4567
page_size: 20
delay_min_ms: 1000
delay_max_ms: 1500
special_keyword_threshold: 3

# API Keys
gemini_api_key: "YOUR_GEMINI_API_KEY_HERE"

stellenwerk_link: "https://www.stellenwerk.de/hamburg"
stellenwerk_pages: 6

stepstone_link: "https://www.stepstone.de/jobs/teilzeit/in-hamburg?action=facet_selected%3bdisciplines%3bIngenieurwesen&wt=80002&di=IT&di=Ingenieurwesen"
stepstone_pages: 4
keywords:
  - "Werkstudent"
  - "Werkstudent:in"
  - "Werkstudent*in"
  - "working student"
  - "Studierende"
  - "Informatik"
  - "Computer"
  - "Büro"
  - "Office"
  - "Working Student"
  - "Praktikum"
  - "Praktikant"
  - "Junior"
  - "Machine Learning"
  - "Deep Learning"
  - "Computer Vision"
  - "Engineer"
  - "Entwickler"
  - "Data Engineer"
  - "Data Scientist"
  - "NLP"
  - "APP"
  - "Mobile"
  - "Application"
  - "Python"
  - "PyTorch"
  - "TensorFlow"
  - "Scikit-learn"
  - "OpenCV"
  - "Image Segmentation"
  - "Predictive Modeling"
  - "Feature Engineering"
  - "Git"
  - "14€"
  - "14 €"
  - "15€"
  - "15 €"
  - "16€"
  - "16 €"
  - "17€"
  - "17 €"
  - "18€"
  - "18 €"
  - "19€"
  - "19 €"
  - "20€"
  - "20 €"
  - "Excel"
  - "CNN"
  - "SVM"
  - "LLM"
  - "Backend"
  - "Full Stack"
  - "C#"
  - ".NET"
  - "ASP.NET Core"
  - "Web API"
  - "SignalR"
  - "Entity Framework"
  - "React"
  - "JavaScript"
  - "Java"
  - "C++"
  - "Onion Architecture"
  - "MVC"
  - "Apache"
  - "Cordova"
  - "IoT Engineer"
  - "Embedded"
  - "Systemautomatisierung"
  - "Automation"
  - "ESP32"
  - "Arduino"
  - "MQTT"
  - "Docker"
  - "Git"
  - "CI/CD"
  - "Linux"
  - "Bash"
  - "SQL"
  - "Server"
  - "IT"
  - "IT-Support"
  - "IT-Administration"
  - "Qualitätssicherung"
  - "Testing"
  - "Machine Learning"
  - "ML"
  - "AI"
  - "KI"
  - "Python"
  - "Computer Vision"
  - "Data Engineer"
  - "Softwareentwickler"
  - "Software Engineer"
  - "Backend"
  - "Full Stack"
  - "C#"
  - ".NET"
  - "Java"
  - "C++"
  - "IoT"
  - "IT-Administration"
  - "Qualitätssicherung"
  - "Software"
  - "Backend"
  - "Developer"
  - "Development"
  - "Praktikum"
  - "Junior"
  - "Informatik"
  - "Hilfskraft"
  - "Studentische"
  - "Embedded Systems"
  - "Hardware Engineer"
  - "Sensoren"
  - "Scientist"
  - "Research"
  - "Software"
  - "Support"
  - "Website"
  - "Wordpress"
  - "Bar"
  - "Restaurant"
  - "Aushilfe"
negative_keywords:
  - "Senior"
  - "Lead"
  - "Manager"
  - "Expert"
  - "Principal"
  - "Head of"
  - "Leitung"
  - "MRI"
  - "Vollzeit"
  - "Full-time"
  - "C1"
  - "C2"
  - "Bauingenieur"
  - "Ingenieurbau"
  - "Verkauf"
  - "Bereichsleiter"
  - "Verkäufer"
  - "Tiefbau"
  - "SAP"
  - "Deutschkenntnisse"
  - "Bauprojekte"
  - "mehrjähriger Erfahrung"
  - "years of experience"
  - "Kundenanfragen"
  - "Kundenservice"
  - " Telefon"
  - "Bautechnik"
  - "Bauingenieurwesen"
  - "Architektur"
  - "Auditor"
  - "TGA"
  - "drei Jahre Berufserfahrung"
  - "zwei Jahre Berufserfahrung"
  - "vier Jahre Berufserfahrung"
  - "fünf Jahre Berufserfahrung"
  - "zwei Jahre Erfahrung"
  - "drei Jahre Erfahrung"
  - "vier Jahre Erfahrung"
  - "fünf Jahre Erfahrung"
  - "1 Jahre Erfahrung"
  - "2 Jahre Erfahrung"
  - "3 Jahre Erfahrung"
  - "4 Jahre Erfahrung" 
  - "5 Jahre Erfahrung"
  - "6 Jahre Erfahrung"
  - "7 Jahre Erfahrung"
  - "8 Jahre Erfahrung"
  - "9 Jahre Erfahrung"
  - "Hochbau"
  - "Consultant"
  - "BI"
  - "SPS"
  - "DESY"
  - "TwinCAT"
  - "Mehrjährige"
  - "Mehrjährig"
  - "Bauingenieurin"
  - "Führerschein"
  - "Bauingenieurwesen"
  - "Grafikdesign"
  - "Erzieher*in"
  - "Erzieher"
  - "Experte"
  - "Elektrotechnik"
  - "Lagepläne"
  - "Wirtschaftsingenieurwesen"
  - "VERMARKTUNG"
  - "Vertrieb"
  - "Wirtschaftsingenieurwesen"
  - "Immobilienverwaltung"
  - "Wirtschaftswissenschaften"
  - "Forderungsmanagement"
  - "Nachhilfe in Deutsch"
  - "Zahnmedizin"
  - "Medizintechnik"
  - "Architektur"
  - "Ausbildung"
  - "Verhandlungssicher"
  - "verhandlungssichere"
  - "Pharmazeut"
  - "zielgruppengerecht"
  - "Marketing"
  - "Produktionstechnik"
