services:
  jobfinder:
    build: .
    container_name: jobfinder_app
    ports:
      - "4567:4567"
    volumes:
      - ./jobs.db:/app/jobs.db
      - ./config.yml:/app/config.yml
      - ./llm_instruction.txt:/app/llm_instruction.txt
      - ./cvs:/app/cvs
      - ./static:/app/static
      - ./templates:/app/templates
    restart: unless-stopped
